<!DOCTYPE html>
<html>
<style>
body {
 font-family: Roboto, sans-serif;
 font-size: 100%;
}
#big_div {
  width: 40%;
  margin: auto;
  min-height: 20px;
  padding: 19px;
  margin-top: 20px;
  margin-bottom: 20px;
  background-color: #f5f5f5;
  border: 1px solid #e3e3e3;
  border-radius: 4px;
}
.form-control {
    display: block;
    margin: 10px 5px;
    width: 70%;
    height: 24px;
    padding: 6px 12px;
    font-size: 14px;
    line-height: 1.42857143;
    color: #555;
    background-color: #fff;
    background-image: none;
    border: 1px solid #ccc;
    border-radius: 4px;
    -webkit-box-shadow: inset 0 1px 1px rgba(0,0,0,.075);
    box-shadow: inset 0 1px 1px rgba(0,0,0,.075);
    -webkit-transition: border-color ease-in-out .15s,-webkit-box-shadow ease-in-out .15s;
    -o-transition: border-color ease-in-out .15s,box-shadow ease-in-out .15s;
    transition: border-color ease-in-out .15s,box-shadow ease-in-out .15s;
}

label {
    display: inline-block;
    max-width: 100%;
    margin: 5px;
    font-weight: 500;
    font-size: 1.1em;
}

.btn-success:active, .btn-success.active, .open>.dropdown-toggle.btn-success {
    background-image: none;
}

.btn-success:hover, .btn-success:focus, .btn-success:active, .btn-success.active, .open>.dropdown-toggle.btn-success {
    color: #fff;
    background-color: #449d44;
    border-color: #398439;
}
.btn:active, .btn.active {
    background-image: none;
    outline: 0;
    -webkit-box-shadow: inset 0 3px 5px rgba(0,0,0,.125);
    box-shadow: inset 0 3px 5px rgba(0,0,0,.125);
}
.btn:hover, .btn:focus {
    color: #333;
    text-decoration: none;
}
button, html input[type=button], input[type=reset], input[type=submit] {
    -webkit-appearance: button;
    cursor: pointer;
}
.btn {
    font-size: 12px;
}
.btn-success {
    color: #fff;
    background-color: #5cb85c;
    border-color: #4cae4c;
}
.btn {
    display: inline-block;
    padding: 6px 12px;
    margin-bottom: 0;
    font-size: 14px;
    font-weight: 400;
    line-height: 1.42857143;
    text-align: center;
    white-space: nowrap;
    vertical-align: middle;
    cursor: pointer;
    -webkit-user-select: none;
    -moz-user-select: none;
    -ms-user-select: none;
    user-select: none;
    background-image: none;
    border: 1px solid transparent;
    border-radius: 4px;
}
</style>
<body>
  <div id="big_div">
    <h2 style="text-align:center">Loomis API Registration</h2>
    <p>
       <span><img src="/images/header_bg_express.png"  /></span>
    </p>
      <form action="/mode/canparapi" method="POST">
          <input type="hidden" name="shopify" value ="<?php echo $data->shop; ?>">
      <label for="shop">Shopify Store Name</label>
      <input id="shop" type="text" name="shop" class="form-control" />
      <label for="shipper_num">Loomis Shipper Number</label>
      <input id="shipper_num" type="text" name="shipper_num" class="form-control" />
      <label for="shipper_password">Loomis Shipper Password</label>
      <input id="shipper_password" type="text" name="shipper_password" class="form-control" />
      <label for="user_id">Loomis Shipper User ID</label>
      <input id="user_id" type="text" name="user_id" class="form-control" />
      <input type="submit" value="Login" class="btn btn-success">
   </form>
  </div>
</body>
</html>
